### ISSUE TITLE
Pagination reliance on finishing scrolling

### ISSUE THREAD

**Issue by kachnitel** [keboola/juicer#3]
The scroller only resets itself once it returns a `false` upon a scroll is determined not to continue. 

This is confusing in the code to see when does the reset actually happen, and if a scroller is shared between jobs AND not "finished", it would not reset, which is hardly useful anywhere ever.

The solution probably shouldn't be changing the way the scroller resets, though resetting in `getFirstRequest` might be one. 
A better solution would probably be having a new instance of the scroller for each job.

**Comment by kachnitel** [comment]
```


    public function testMultipleJobsSameScroller()
    {
        $config = $this->getScrollerConfig();
        $config['default'] = 'page';
        $scroller = new MultipleScroller($config);

        $client = RestClient::create();

        $config1 = new JobConfig('none', [
            'endpoint' => 'data1'
        ]);
        $config2 = new JobConfig('none', [
            'endpoint' => 'data2'
        ]);

        $response = (object) [
            'data' => [1,2]
        ];

        $first1 = $scroller->getFirstRequest($client, $config1);
        $second1 = $scroller->getNextRequest($client, $config1, $response, $response->data);
        // $last1 = $scroller->getNextRequest($client, $config1, [], []);

        $first2 = $scroller->getFirstRequest($client, $config2);
        $second2 = $scroller->getNextRequest($client, $config2, $response, $response->data);

        var_dump($first1, $second1, $first2, $second2);
    }
```

Without the `$last`, the followup requests will continue the increments from previous "job"

**Comment by odinuv** [comment]
A new instance of scroller is now used for each job https://github.com/keboola/generic-extractor/commit/535b116e8e98577987d3d600ecb63eb153ef9e72
